name: backend
description: A fintech backend API with user registration
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0